import pytest

from conftest import FIXTURES
from rc import locks
from rc.errors import RcError

YT_DLP = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    echo 'yt-dlp[default,curl-cffi,pin,pin-curl-cffi]==2026.08.19' | uv pip compile --universal "
    "--generate-hashes --only-binary :all: --python-version 3.14 --exclude-newer '7 days' "
    "--exclude-newer-package yt-dlp=false - -o requirements.lock\n"
    "brotli==1.2.0 \\\n    --hash=sha256:" + "0" * 64 + "\n"
)
DENO = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    echo 'yt-dlp[pin-deno]==2026.08.19' | uv pip compile --universal --generate-hashes --only-binary :all: "
    "--python-version 3.14 --exclude-newer '7 days' --exclude-newer-package yt-dlp=false --no-emit-package yt-dlp "
    "- -o requirements-deno.lock\n"
)


@pytest.mark.parametrize("text,file", [(YT_DLP, "requirements.lock"), (DENO, "requirements-deno.lock")])
def test_recipe_round_trip(text, file):
    recipe = locks.parse_recipe(text, file, "yt-dlp")
    assert f"#    {recipe.header_command('2026.08.19')}" == text.splitlines()[1]


OWN = "--exclude-newer-package yt-dlp=false"
EJS = YT_DLP.replace(OWN, f"{OWN} --exclude-newer-package yt-dlp-ejs=false")


def test_recipe_with_exempt_dependency():
    recipe = locks.parse_recipe(EJS, "requirements.lock", "yt-dlp")
    assert recipe.exempt == ("yt-dlp-ejs",)
    assert f"#    {recipe.header_command('2026.08.19')}" == EJS.splitlines()[1]
    assert recipe.options()[-4:] == ["--exclude-newer-package", "yt-dlp=false", "--exclude-newer-package", "yt-dlp-ejs=false"]


@pytest.mark.parametrize(
    "value",
    ["yt-dlp-ejs=false --exclude-newer-package yt-dlp-ejs=false", "yt_dlp_ejs=false", "yt-dlp-ejs=2026-01-01", "yt-dlp=false"],
)
def test_recipe_rejects_bad_exemptions(value):
    text = YT_DLP.replace(OWN, f"{OWN} --exclude-newer-package {value}")
    with pytest.raises(RcError):
        locks.parse_recipe(text, "requirements.lock", "yt-dlp")


def test_recipe_needs_the_project_exemption():
    text = YT_DLP.replace(OWN, "--exclude-newer-package yt-dlp-ejs=false")
    with pytest.raises(RcError, match="must use"):
        locks.parse_recipe(text, "requirements.lock", "yt-dlp")


def test_recipe_values():
    recipe = locks.parse_recipe(DENO, "requirements-deno.lock", "yt_dlp")
    assert recipe.extras == ("pin-deno",) and recipe.no_emit == ("yt-dlp",) and recipe.python_version == "3.14"
    assert recipe.requirement("2026.09.20") == "yt-dlp[pin-deno]==2026.09.20"
    assert recipe.options()[-4:] == ["--exclude-newer-package", "yt-dlp=false", "--no-emit-package", "yt-dlp"]


@pytest.mark.parametrize(
    "change,message",
    [
        (("--only-binary :all:", "--index-url https://evil.example"), "unsupported uv option"),
        (("--only-binary :all: ", ""), "must use"),
        (("'yt-dlp[", "'other["), "requirement must be yt-dlp"),
        (("--exclude-newer '7 days'", "--exclude-newer '7 days; id'"), "unsupported uv option"),
        (("requirements.lock\n", "other.lock\n"), "second line"),
        (("# This file", "# That file"), "uv header"),
    ],
)
def test_recipe_rejects(change, message):
    with pytest.raises(RcError, match=message):
        locks.parse_recipe(YT_DLP.replace(*change), "requirements.lock", "yt-dlp")


def test_check_lock():
    recipe = locks.parse_recipe(YT_DLP, "requirements.lock", "yt-dlp")
    good = f"{locks.HEADER}\n#    {recipe.header_command('2026.09.20')}\nyt-dlp==2026.9.20 \\\n    --hash=sha256:{'1' * 64}\n"
    locks.check_lock(good.encode(), recipe, "2026.09.20")
    with pytest.raises(RcError, match="yt-dlp is missing"):
        locks.check_lock(good.replace("yt-dlp==", "other==").encode(), recipe, "2026.09.20")
    with pytest.raises(RcError, match="unexpected header"):
        locks.check_lock(good.encode(), recipe, "2026.09.21")
    with pytest.raises(RcError, match="no hashes"):
        locks.check_lock(good.replace("--hash=sha256:", "--h=").encode(), recipe, "2026.09.20")


def test_compile_needs_uv(monkeypatch):
    monkeypatch.setattr(locks.shutil, "which", lambda _: None)
    with pytest.raises(RcError, match="uv is not installed"):
        locks.compile_lock(locks.parse_recipe(YT_DLP, "requirements.lock", "yt-dlp"), "2026.09.20")


def test_new_recipe_writes_the_expected_header():
    recipe, version = locks.new_recipe("requirements-deno.lock", "yt-dlp[pin-deno]==2026.08.19", "3.14", ("yt-dlp",))
    assert f"#    {recipe.header_command(version)}" == DENO.splitlines()[1]
    recipe, version = locks.new_recipe(
        "requirements.lock", "yt-dlp[default,curl-cffi,pin,pin-curl-cffi]==2026.08.19", "3.14", exempt=("yt_dlp_ejs",)
    )
    assert f"#    {recipe.header_command(version)}" == EJS.splitlines()[1]
    with pytest.raises(RcError, match="normalized name"):
        locks.new_recipe("requirements.lock", "yt-dlp==2026.08.19", "3.14", exempt=("yt-dlp",))
    with pytest.raises(RcError):
        locks.new_recipe("requirements.lock", "yt-dlp>=1", "3.14")


def test_lock_command(tmp_path, monkeypatch):
    from rc import cli

    calls = []
    monkeypatch.setattr(locks, "compile_lock", lambda recipe, version: calls.append((recipe, version)) or b"lock\n")
    (tmp_path / "package.yml").write_text((FIXTURES / "yt-dlp" / "package.yml").read_text())
    (tmp_path / "requirements.lock").write_text(YT_DLP)
    assert cli.main(["lock", str(tmp_path / "requirements.lock")]) == 0
    assert calls[-1][1] == "2026.08.19" and calls[-1][0].extras == ("default", "curl-cffi", "pin", "pin-curl-cffi")
    assert (tmp_path / "requirements.lock").read_text() == "lock\n"
    assert cli.main(["lock", str(tmp_path / "new.lock"), "--requirement", "streamlink==8.6.1"]) == 0
    assert calls[-1][0].project == "streamlink" and calls[-1][1] == "8.6.1"
    (tmp_path / "requirements.lock").write_text(YT_DLP)
    assert cli.main(["lock", str(tmp_path / "requirements.lock"), "--exempt", "yt-dlp-ejs"]) == 0
    assert calls[-1][0].exempt == ("yt-dlp-ejs",)


def test_uv_does_not_see_the_tokens(tmp_path, monkeypatch):
    seen = {}

    def fake_run(cmd, input, text, capture_output, cwd, env, timeout):
        seen.update(env)
        out = cmd[cmd.index("-o") + 1]
        recipe = locks.parse_recipe(YT_DLP, "requirements.lock", "yt-dlp")
        header = f"{locks.HEADER}\n#    {recipe.header_command('2026.09.20')}\n"
        open(out, "w").write(header + f"yt-dlp==2026.9.20 \\\n    --hash=sha256:{'1' * 64}\n")
        return type("P", (), {"returncode": 0, "stdout": "", "stderr": ""})()

    monkeypatch.setenv("RC_WRITE_TOKEN", "secret")
    monkeypatch.setenv("GITHUB_TOKEN", "secret")
    monkeypatch.setattr(locks.subprocess, "run", fake_run)
    recipe = locks.parse_recipe(YT_DLP, "requirements.lock", "yt-dlp")
    locks.compile_lock(recipe, "2026.09.20", uv="/usr/bin/uv")
    assert "RC_WRITE_TOKEN" not in seen and "GITHUB_TOKEN" not in seen and seen["UV_NO_CONFIG"] == "1"
