"""Hash-locked requirements files of Python packages.

Each lock file names the command that produced it in its header:

    #    echo 'yt-dlp[default,curl-cffi]==2026.08.19' | uv pip compile --universal ... - -o requirements.lock

The reconciler reads the requirement and the options from that line,
checks them against a fixed list, and runs the same command with the new
version. `--only-binary :all:` means resolving never runs code from a
package, and `--exclude-newer` keeps dependencies released in the last
days out of the lock; the package itself is exempt, since its release has
already passed the cooldown and the provenance check. A lock may exempt a
few more packages with further `--exclude-newer-package NAME=false`
options, for dependencies the package pins exactly and releases on the
same day, such as yt-dlp-ejs for yt-dlp.
"""

import dataclasses
import os
import re
import shlex
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

from rc import names
from rc.errors import RcError

HEADER = "# This file was autogenerated by uv via the following command:"
_COMMAND = re.compile(
    r"^#    echo '(?P<req>[^'\n]{1,200})' \| uv pip compile (?P<args>[^\n]{1,500}) - -o (?P<out>[A-Za-z0-9._-]{1,128})$",
    re.M,
)
_REQUIREMENT = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]{0,99})(?:\[(?P<extras>[a-z0-9-]+(?:,[a-z0-9-]+)*)\])?==(?P<version>[0-9][0-9A-Za-z.]{0,63})$"
)
_PYTHON = re.compile(r"^3\.[0-9]{1,2}$")
_DURATION = re.compile(r"^[0-9]{1,3} (?:hours|days|weeks?)$")
_PACKAGE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,99}$")
MAX_EXEMPT = 5
TIMEOUT = 600
_ENV_KEEP = ("PATH", "HOME", "LANG", "LC_ALL", "TMPDIR", "SSL_CERT_FILE", "SSL_CERT_DIR", "HTTPS_PROXY", "NO_PROXY")


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass(frozen=True)
class Recipe:
    file: str
    project: str
    extras: tuple[str, ...]
    python_version: str
    exclude_newer: str
    no_emit: tuple[str, ...]
    exempt: tuple[str, ...] = ()  # besides the project itself

    def requirement(self, version: str) -> str:
        extras = f"[{','.join(self.extras)}]" if self.extras else ""
        return f"{self.project}{extras}=={version}"

    def options(self) -> list[str]:
        args = [
            "--universal",
            "--generate-hashes",
            "--only-binary",
            ":all:",
            "--python-version",
            self.python_version,
            "--exclude-newer",
            self.exclude_newer,
            "--exclude-newer-package",
            f"{normalize(self.project)}=false",
        ]
        for package in self.exempt:
            args += ["--exclude-newer-package", f"{package}=false"]
        for package in self.no_emit:
            args += ["--no-emit-package", package]
        return args

    def header_command(self, version: str) -> str:
        return (
            f"echo '{self.requirement(version)}' | uv pip compile {shlex.join(self.options())} - -o {self.file}"
        )


def parse_recipe(text: str, file: str, project: str) -> Recipe:
    """Read how a lock file was made. Only the options rc itself writes are accepted."""
    if not names.FILE_NAME.match(file):
        raise RcError(f"bad lock file name {file!r}")
    lines = text.splitlines()
    if len(lines) < 2 or lines[0] != HEADER:
        raise RcError(f"{file} does not start with the uv header")
    m = _COMMAND.match(lines[1])
    if not m or m.group("out") != file:
        raise RcError(f"{file}: the second line is not the expected 'echo ... | uv pip compile ...' command")
    req = _REQUIREMENT.match(m.group("req"))
    if not req or normalize(req.group("name")) != normalize(project):
        raise RcError(f"{file}: the requirement must be {project}==<version>, optionally with extras")
    try:
        words = shlex.split(m.group("args"))
    except ValueError:
        raise RcError(f"{file}: cannot parse the uv options") from None
    python_version = exclude_newer = None
    own = False
    exempt: list[str] = []
    no_emit: list[str] = []
    flags = {"--universal": False, "--generate-hashes": False}
    only_binary = False
    i = 0
    while i < len(words):
        word = words[i]
        value = words[i + 1] if i + 1 < len(words) else ""
        if word in flags:
            flags[word] = True
            i += 1
            continue
        if word == "--only-binary" and value == ":all:":
            only_binary = True
        elif word == "--python-version" and _PYTHON.match(value):
            python_version = value
        elif word == "--exclude-newer" and _DURATION.match(value):
            exclude_newer = value
        elif word == "--exclude-newer-package" and value == f"{normalize(project)}=false" and not own:
            own = True
        elif word == "--exclude-newer-package" and value.endswith("=false") and value[: -len("=false")] not in exempt:
            exempt.append(check_exempt(value[: -len("=false")], project))
        elif word == "--no-emit-package" and _PACKAGE.match(value):
            no_emit.append(value)
        else:
            raise RcError(f"{file}: unsupported uv option {word!r}")
        i += 2
    if not all(flags.values()) or not only_binary or not python_version or not exclude_newer or not own:
        raise RcError(
            f"{file}: the command must use --universal --generate-hashes --only-binary :all: "
            f"--python-version, --exclude-newer and --exclude-newer-package {normalize(project)}=false"
        )
    if len(exempt) > MAX_EXEMPT:
        raise RcError(f"{file}: more than {MAX_EXEMPT} packages are exempt from --exclude-newer")
    extras = tuple(req.group("extras").split(",")) if req.group("extras") else ()
    return Recipe(file, req.group("name"), extras, python_version, exclude_newer, tuple(no_emit), tuple(exempt))


def check_exempt(name: str, project: str) -> str:
    """A package that may skip --exclude-newer, written the way the header has it."""
    if not _PACKAGE.match(name) or normalize(name) != name or name == normalize(project):
        raise RcError(f"bad package for --exclude-newer-package: {name!r} (use the normalized name, other than {project})")
    return name


def with_exempt(recipe: Recipe, names_: tuple[str, ...]) -> Recipe:
    """The recipe with more packages exempt from --exclude-newer."""
    exempt = list(recipe.exempt)
    for name in names_:
        name = check_exempt(normalize(name), recipe.project)
        if name not in exempt:
            exempt.append(name)
    if len(exempt) > MAX_EXEMPT:
        raise RcError(f"{recipe.file}: more than {MAX_EXEMPT} packages are exempt from --exclude-newer")
    return dataclasses.replace(recipe, exempt=tuple(exempt))


def new_recipe(
    file: str, requirement: str, python_version: str, no_emit: tuple[str, ...] = (), exempt: tuple[str, ...] = ()
) -> tuple[Recipe, str]:
    """A recipe for a lock file that does not exist yet, and the version it pins."""
    m = _REQUIREMENT.match(requirement)
    if not m:
        raise RcError(f"{requirement!r} must look like name==version or name[extra,...]==version")
    if not _PYTHON.match(python_version):
        raise RcError(f"bad Python version {python_version!r}")
    for package in no_emit:
        if not _PACKAGE.match(package):
            raise RcError(f"bad package name {package!r}")
    if not names.FILE_NAME.match(file):
        raise RcError(f"bad lock file name {file!r}")
    extras = tuple(m.group("extras").split(",")) if m.group("extras") else ()
    recipe = Recipe(file, m.group("name"), extras, python_version, "7 days", tuple(no_emit))
    return with_exempt(recipe, exempt), m.group("version")


def compile_lock(recipe: Recipe, version: str, uv: str | None = None) -> bytes:
    """Run uv pip compile for a new version and return the lock file it writes."""
    uv = uv or shutil.which("uv")
    if not uv:
        raise RcError("uv is not installed")
    requirement = recipe.requirement(version)
    if not _REQUIREMENT.match(requirement):
        raise RcError(f"refusing to lock {requirement!r}")
    with tempfile.TemporaryDirectory(prefix="rc-lock-") as tmp:
        out = Path(tmp) / recipe.file
        # Only what uv needs: the tokens of the reconcile job stay out of its environment.
        env = {k: v for k, v in os.environ.items() if k in _ENV_KEEP}
        env.update({"UV_CACHE_DIR": str(Path(tmp) / "cache"), "UV_NO_CONFIG": "1", "NO_COLOR": "1"})
        cmd = [
            uv,
            "pip",
            "compile",
            *recipe.options(),
            "--custom-compile-command",
            recipe.header_command(version),
            "--no-progress",
            "--quiet",
            "-",
            "-o",
            str(out),
        ]
        try:
            proc = subprocess.run(  # noqa: S603 - fixed argv, no shell
                cmd, input=requirement + "\n", text=True, capture_output=True, cwd=tmp, env=env, timeout=TIMEOUT
            )
        except subprocess.TimeoutExpired:
            raise RcError(f"uv pip compile for {recipe.file} timed out") from None
        if proc.returncode != 0:
            detail = (proc.stderr or proc.stdout).strip().splitlines()[-5:]
            raise RcError(f"uv pip compile for {recipe.file} failed: " + " / ".join(detail))
        data = out.read_bytes()
    check_lock(data, recipe, version)
    return data


def pins(data: bytes) -> dict[str, set[str]]:
    """Normalized name to the versions a lock file pins (one per marker set)."""
    out: dict[str, set[str]] = {}
    for line in data.decode("utf-8").splitlines():
        if not line or line.startswith((" ", "#")):
            continue
        requirement = line.split(";", 1)[0].removesuffix("\\").strip()
        name, sep, version = requirement.partition("==")
        if sep:
            out.setdefault(normalize(name.split("[", 1)[0].strip()), set()).add(version.strip())
    return out


def check_lock(data: bytes, recipe: Recipe, version: str) -> None:
    text = data.decode("utf-8")
    lines = text.splitlines()
    if len(lines) < 3 or lines[0] != HEADER or lines[1] != f"#    {recipe.header_command(version)}":
        raise RcError(f"{recipe.file}: uv wrote an unexpected header")
    pins = [line for line in lines if line and not line.startswith((" ", "#"))]
    if not pins:
        raise RcError(f"{recipe.file}: uv wrote no requirements")
    for pin in pins:
        if "==" not in pin or not pin.rstrip().endswith("\\"):
            raise RcError(f"{recipe.file}: unexpected line {pin[:80]!r}")
    if "--hash=sha256:" not in text:
        raise RcError(f"{recipe.file}: uv wrote no hashes")
    if normalize(recipe.project) not in {normalize(n) for n in recipe.no_emit}:
        wanted = f"{normalize(recipe.project)}=="
        if not any(normalize(p.split("==", 1)[0].split("[")[0]) + "==" == wanted for p in pins):
            raise RcError(f"{recipe.file}: {recipe.project} is missing from the lock")
